### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by wynntw** [davidjesusacu/polyrnn-pp#11]
After I changed the version of tf to 1.3.0, it turned out to be
<img width="1440" alt="2018-06-25 3 37 51" src="https://user-images.githubusercontent.com/37532387/41836657-fae065ec-788d-11e8-88fa-e914fc1db53a.png">

How can I fix with it?

**Comment by Max-Fu** [comment]
1) I assume you have used a different version of cuda and cudnn, therefore, you have to download cudnn 6 with CUDA 8 (to your virtualenv)
2) You then have to set LD_LIBRARY_PATH under wynn_env/bin/activate (yes, activate itself is a file) so that your tensorflow can find cuda and cudnn. 

Best,
Max

**Comment by amlankar** [comment]
That is correct, the error seems to be with cudnn-6 .so files not being in your LD_LIBRARY_PATH

**Comment by davidjesusacu** [comment]
Yes, as stated before, this is a problem of the framework installation. 
There is a good tutorial here: https://www.tensorflow.org/install/install_linux
Also by looking at the logs, it seems you are using python 3. 
Closing for now.
