### ISSUE TITLE
How can i  make annotations of objects interactively using humans-in-the-loop?

### ISSUE THREAD

**Issue by Jacoobr** [davidjesusacu/polyrnn-pp#16]
Hello davidjesusacu, would you mind provide me more details about how to implement interactively annotate when i predict polygonal annotations of an object?

**Comment by amlankar** [comment]
Hi, if you're asking for the code for this, then it is in the works right now.

If you are asking theoretically, then the idea is to remember which time step the correct was made in, and force-feed the RNN the vertex at that time step, instead of letting it take its own output. Does that make sense?

**Comment by Jacoobr** [comment]
@amlankar Thanks for your reply, I can see the result when I correct one vertex that was produced not good by the RNN  on your great online tools, then the whole vertexts except the vertext that I corrected  will be reproduced (predicted) by the model nicely. But there are two questions as follows confused me: 1 )  I think when the vertex  at  time step _t_ which corrected by me, then the next whole vertexs  after time step _t_ will be predicted once again depend on the vertext that I corrected. But the vertext before time step _t_ should not  be re-predicted because the lstm RNN net work is a sequence structure. In other words, the vertext corrected  at time step _t_ can't donate to the vertexts before that time step. How do you think of my thought?  2)  Would you mind provide me with the training network? I plan to train my own model on  MRI medical images data set about MRI segmentation task research. To be honest, I'm a newbie and  I have taken a few days on trying to write the training network according to your [CVPR 2018](https://arxiv.org/abs/1803.09693) paper. But I get nowhere about it. Your help will help me a lot with my work . This is my email address _xiaojianli@stu.xjtu.edu.cn_.  Look forward to your favourable reply. Thanks.

**Comment by amlankar** [comment]
Hi @Jacoobr,

1) Thanks for trying it out! You are correct, when you correct the vertex at time step T, the vertices before that do not get corrected. In our tool, when you drag a vertex, the vertices that get coloured red will not move. This is why the right method of interactive annotation is to move the first vertex that is wrong in the direction of RNN prediction to the right point (the direction is specified by the green line leaving from the green point in our tool).

2) We are working on preparing a training code release that is clean and modular. We will update on the repository as soon as it is done!

**Comment by yshvrdhn** [comment]
Hi any timeline as to when will the correction code, as well as training code, will be made available? Thank you for releasing the inference code.

**Comment by amlankar** [comment]
It'll be released by the end of the summer

**Comment by lucasjinreal** [comment]
@amlankar Wish for your work and the release of training codes. This work really marvelous!

**Comment by amlankar** [comment]
We have released the code now! Checkout https://github.com/fidler-lab/polyrnn-pp-pytorch
