### ISSUE TITLE
demo not responding

### ISSUE THREAD

**Issue by memphizz** [davidjesusacu/polyrnn-pp#17]
the online demo doesn't create annotation on the demo images. Looks like gpu backend is not working.

**Comment by amlankar** [comment]
I just took a look at the log files, seems like the image that caused an error recently was uploaded and is in an unsupported format. Running skimage.io.imread() on the image returns an array of size (2,), with the first element being the actual image. 

https://github.com/scikit-image/scikit-image/issues/2406

From this issue, it seems like the image you uploaded is somehow a multiframe image. I tried reading it with PIL, and im.nframes gives me 2. Right now, I would say we do not support multiframe images, but I will see what we can do on the backend without breaking anything.

Thanks for reporting!

**Comment by memphizz** [comment]
The issue applies to the images that come with the demo like "Medical 1". I can't generate annotation for any images.

**Comment by amlankar** [comment]
I can't reproduce this error, things seem to be working for me, and there are no errors on the backend. This could be a JS issue, could you check if there are any errors on the console in your browser? Which browser are you using?

**Comment by memphizz** [comment]
I am using chrome

**Comment by amlankar** [comment]
Could you press Ctrl + Shift + I after the error and share the console output?

**Comment by memphizz** [comment]
same with FireFox. There are no errors and I don't see any console output. The three circles of the demo tool are moving but it doesn't create the annotations.

**Comment by memphizz** [comment]
I am getting this error using IE:
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, http://download.microsoft.com/download/B/9/F/B9FF9327-7A72-4165-BF91-9B7EEB6C579B/DeviceList.json

**Comment by amlankar** [comment]
From what I can figure out by reading, it seems like this is a client side network error, or could be caused because of missing headers on a response to a POST request. Since I can't reproduce, it's hard to debug.

**Comment by memphizz** [comment]
I tried it at home without any issues. It seems that it's blocked at work.
