### ISSUE TITLE
while running demo on my own data 

### ISSUE THREAD

**Issue by DODoubleJ** [davidjesusacu/polyrnn-pp#18]
When I replaced the demo images with my own data, an error occurred and  it told me the shape of my images tensor is not the required shape:[1,224,224], so if I want to run demo on my own data, the only way I can choose is change the size of my data, because if I change the default tensor in the code, I will encounter more troubles, something like changing the pretrained model.
So if the code is only suitable for the images in the shape of 224*224? I'm confused.

**Comment by arieling** [comment]
Yes we resize all image to 224*224 as input

**Comment by lucasjinreal** [comment]
@arieling From your Youtube demo video, you are crop a patch from image and then predict polygons from it. Does the input is just the croped path or the whole image?

**Comment by arieling** [comment]
@jinfagang we shore images in our server. In our demo front-end gives bounding box to backend and our dataProvider crops the full image according to it.

**Comment by yohacai** [comment]
Hi, how to crop the full image according to the bounding box ?And is this the latest model？

**Comment by arieling** [comment]
@yohacai That part of code is not released yet. Hopefully we will release training code & full model & data & demo this week.

**Comment by lucasjinreal** [comment]
@arieling Hoping for it

**Comment by meatball-guy** [comment]
Thank you for the hard work! Am looking forward to it

**Comment by arieling** [comment]
Code released. Check https://github.com/fidler-lab/polyrnn-pp-pytorch and sign up to get our full code.
