### ISSUE TITLE
Regarding the values passed again to the pytorch model for the corrected coordinates 

### ISSUE THREAD

**Issue by abinjoabraham** [davidjesusacu/polyrnn-pp#21]

**Comment by abinjoabraham** [comment]
I was interested in the fixing method while testing the model. Especially about the variable 'instance['fwd_poly']'. I just initially thought this variable is the new value which is generated after the user does the correction interactively. But after printing this fwd_poly of instance it seems like some floating point numbers with values less than 100. If you don't mind can you elaborate how this fwd_poly is populated?

**Comment by amlankar** [comment]
Closing since this is related to the pytorch repo -- fidler-lab/polyrnn-pp-pytorch#9
