### ISSUE TITLE
how can I convert pth to ckpt

### ISSUE THREAD

**Issue by kidting** [davidjesusacu/polyrnn-pp#24]
I got the training code，however the weight file is .pth，how can I convert pth to ckpt so that I can resume train and use this tensorflow demo.
thank you！

**Comment by amlankar** [comment]
This repository provides **inference** code only.

The training code is in [pytorch](https://github.com/fidler-lab/polyrnn-pp-pytorch), and therefore the weights are also provided for pytorch

**Comment by kidting** [comment]
could you please share the training code in tensorflow?

**Comment by kidting** [comment]
> This repository provides **inference** code only.
> 
> The training code is in [pytorch](https://github.com/fidler-lab/polyrnn-pp-pytorch), and therefore the weights are also provided for pytorch
could you please share the training code in tensorflow?

**Comment by kidting** [comment]
@amlankar 
could you please share the training code in tensorflow?

**Comment by arieling** [comment]
sorry we have no plan to release tensorflow training code. Please refer to ours pytorch training script.
