### ISSUE TITLE
Bug in demo_inference.sh

### ISSUE THREAD

**Issue by dheera** [davidjesusacu/polyrnn-pp#3]
ValueError: graph_def is invalid at node u'GatherTree': Input types mismatch (expected 'int32, int32, int32, int32' but got 'int32, int32, int32').

![screenshot from 2018-04-12 22-07-12](https://user-images.githubusercontent.com/1786477/38706748-3e93a1d8-3e63-11e8-8129-6ac39148a8d7.png)

**Comment by amlankar** [comment]
Hi, could you check what version of tensorflow you're using? We support <=1.3.0. issue #2 also had a similar problem.

**Comment by dheera** [comment]
Oh yes, I'm using 1.7. I can't spin up 1.3 on my current machine since I'm using CUDA 9 but I'll try it again later on another machine. Thannks.

**Comment by amlankar** [comment]
Thanks!
