### ISSUE TITLE
Training code request

### ISSUE THREAD

**Issue by 18045623983** [davidjesusacu/polyrnn-pp#5]
I am a student at the University of Engineering. I am very interested in your article, but at the beginning of my study, can you provide the source code of the training process? I would like to use it to compare the study of the article.

**Comment by arieling** [comment]
We plan to share the training code publicly soon and think sharing case by case might not be the best way moving forward. 
Right now, our priority is to release the interactive tool and correction mode graph and then the training code.

While we'll be able to share the code later, we are always open to helping with and answering any specific questions you might have regarding setting it up/reproducing etc.
