### ISSUE TITLE
Training code release date

### ISSUE THREAD

**Issue by serycjon** [davidjesusacu/polyrnn-pp#9]
Hi, when do you approximately expect the training code to be released? At least approximately, like "in one month from now"?

I was greatly disappointed with the original PolyRNN paper, which had "code coming soon" on the project website (and also in the paper itself: "We plan to release our code and create a web-annotation interface running our model at the backend.") for quite a long time.  I have checked frequently only to find, that this promise has simply disappeared one day.  Hope this won't be the case with this paper.

**Comment by amlankar** [comment]
Hi, we are working on this, you could expect it at most by late summer. Thanks!

**Comment by amlankar** [comment]
Hi @serycjon, we have released the training code now! Checkout: https://github.com/fidler-lab/polyrnn-pp-pytorch
